# Generated by Django 2.2.3 on 2019-09-15 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipd',
            fields=[
                ('reason_admission', models.CharField(blank=True, max_length=200)),
                ('provisional_diagnosis', models.CharField(max_length=200)),
                ('ipd_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('bill_responsible', models.CharField(blank=True, max_length=100)),
                ('bill_relation', models.CharField(blank=True, max_length=100)),
                ('date_of_admission', models.DateField(default=datetime.date.today)),
                ('time_of_admission', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('condition_admission', models.CharField(choices=[('Undetermined', 'Undetermined'), ('Stable', 'Stable'), ('Serious', 'Serious')], max_length=20)),
                ('consultant', models.CharField(choices=[('Doctor1', 'Doctor1'), ('Doctor2', 'Doctor2')], max_length=20)),
                ('secondary_consultant', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentGiven',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=100, null=True)),
                ('types_of_doses', models.CharField(blank=True, choices=[('OD', 'OD'), ('BD', 'BD'), ('TDS', 'TDS'), ('QID', 'QID'), ('STAT', 'STAT')], max_length=100)),
                ('route', models.CharField(blank=True, choices=[('Oral', 'Oral'), ('IV', 'IV'), ('IM', 'IM'), ('Other', 'Other'), ('L/A', 'L/A'), ('R/T', 'R/T'), ('S.C', 'S.C'), ('Other', 'Other')], max_length=100)),
                ('number_of_days', models.IntegerField(null=True)),
                ('ipd', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospi.Ipd')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentAdviced',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine', models.CharField(blank=True, max_length=100)),
                ('types_ofdoses', models.CharField(blank=True, max_length=100)),
                ('number_ofdays', models.IntegerField(blank=True)),
                ('discription', models.CharField(max_length=100)),
                ('ipd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospi.Ipd')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.TextField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('ipd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospi.Ipd')),
            ],
        ),
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('opd_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospi.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='ipd',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospi.Patient'),
        ),
        migrations.AddField(
            model_name='ipd',
            name='rooms',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospi.Rooms'),
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('report', models.TextField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('ipd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospi.Ipd')),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_diagnosis', models.CharField(blank=True, max_length=100)),
                ('discharge_condition', models.CharField(max_length=100)),
                ('follow_up_advice', models.CharField(max_length=100)),
                ('type_discharge', models.CharField(choices=[('Discharge', 'Discharge'), ('Dama', 'Dama'), ('Dead', 'Dead'), ('Transfer', 'Transfer')], max_length=30)),
                ('date_of_discharge', models.DateField(default=datetime.date.today)),
                ('time_of_discharge', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('ipd', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospi.Ipd')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.CharField(max_length=50)),
                ('pulse', models.CharField(max_length=50)),
                ('bp', models.CharField(max_length=50)),
                ('rs', models.CharField(max_length=50)),
                ('cvs', models.CharField(max_length=50)),
                ('pa', models.CharField(max_length=50)),
                ('cns', models.CharField(max_length=50)),
                ('pupils', models.CharField(max_length=50)),
                ('planter', models.CharField(max_length=50)),
                ('other', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('ipd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospi.Ipd')),
            ],
        ),
    ]
