# Generated by Django 2.2.3 on 2019-09-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
