# Generated by Django 2.2 on 2020-03-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospi', '0002_auto_20190917_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='ipd',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospi.Ipd'),
        ),
    ]
